[package]
name = "counter"
version = "0.1.0"
authors = ["Max Block <maxblock@pm.me>"]
edition = "2018"


[dependencies]
borsh = "0.9.0"
thiserror = "1.0.25"
solana-program = "1.6.10"

[dev-dependencies]
solana-program-test = "1.6.10"
solana-sdk = "1.6.10"


[lib]
crate-type = ["cdylib", "lib"]