[package]
name = "program"
version = "0.1.0"
authors = ["Max Block <maxblock@pm.me>"]
edition = "2018"


[dependencies]
solana-program = "1.6.10"
spl-token = "3.1.1"


[lib]
crate-type = ["cdylib", "lib"]