[package]
name = "program"
version = "0.1.0"
authors = ["Max Block <maxblock@pm.me>"]
edition = "2018"


[dependencies]
borsh = "0.9.0"
solana-program = "1.6.10"
spl-token = { version = "3.1.1", features = ["no-entrypoint"] }


[lib]
crate-type = ["cdylib", "lib"]