localnet-validator:
	solana-test-validator -r --ledger localnet/ledger

localnet-init:
	solana airdrop 1 localnet/admin.json -u localhost
	solana airdrop 1 localnet/user.json -u localhost

testnet-airdrop:
	solana airdrop 10 localnet/admin.json -u testnet
	solana airdrop 1 localnet/user.json -u testnet

test:
	cd program; cargo test
	cd program; cargo test-bpf

localnet-deploy: test
	cd program; cargo build-bpf
	solana program deploy program/target/deploy/counter.so -u localhost --program-id localnet/program.json

testnet-deploy: test
	cd program; cargo build-bpf
	solana program deploy program/target/deploy/counter.so -u testnet --program-id localnet/program.json --keypair localnet/admin.json --upgrade-authority localnet/admin.json

client:
    cd client; npm install
    cd client; ./node_modules/.bin/ts-node src/main.ts
